# Suggested data paths when using GPT-NeoX locally
{
  # "data-path": "data/pile_00/pile_00_text_document",
  "train-data-paths": [
      "/data/trial_small_v20230701/gpt-neox-bin/wiki_en_20230320_train_filtered_text_document",
      "/data/trial_small_v20230701/gpt-neox-bin/wiki_ja_20230320_train_filtered_text_document"
  ],
  "test-data-paths": [
      "/data/trial_small_v20230701/gpt-neox-bin/wiki_en_20230320_train_filtered_text_document",
      "/data/trial_small_v20230701/gpt-neox-bin/wiki_ja_20230320_train_filtered_text_document"
  ],
  "valid-data-paths": [
      "/data/trial_small_v20230701/gpt-neox-bin/wiki_en_20230320_train_filtered_text_document",
      "/data/trial_small_v20230701/gpt-neox-bin/wiki_ja_20230320_train_filtered_text_document"
  ],

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  # "vocab-file": "data/gpt2-vocab.json",
  # "merge-file": "data/gpt2-merges.txt",
  # "tokenizer-type": "HFTokenizer",
  # "vocab-file": "20B_checkpoints/20B_tokenizer.json",
  "tokenizer-type": "JapaneseSentencePiece",
  "vocab-file": "/data/tokenizer/v1_20230628/cc100_ja30K_en20K.symbolRemoved.vocab.reestimated.model",

  "save": "/model/kurita/gpt-neox/checkpoints.trial_small_v20230701.125M.2",
  "load": "/model/kurita/gpt-neox/checkpoints.trial_small_v20230701.125M.2",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "llm-jp"
}
